apiVersion: v1
data:
  secretkey: ZUV5Tk5BMSt5N0NBdUV2Y2t4eWY2QlkvWDF5Z29Eb0ZEdUxZYVJ5S1cyTmsxVTRjMElWSHFRRGJ5NXcrYW94NwpCYXo5UEphVUFEUm94blVNQTFkNzdKOGI3Q0hweHdlMFh1Y3JQM2ptRXNVQ1hqOEpPUDV0b2MxR1Q3b2JCMFgrCkJZeFN1L1MzQk5wU2dZdkJPSlIzWC9nb3pyY1hHRWRQbE5RSXEvcUplaWM9
kind: Secret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
